### ISSUE TITLE
is there a version for supporting ros2 foxy?

### ISSUE THREAD

**Issue by Bedoctor** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_depth#15]
is there a version for supporting ros2 foxy? if yes, How to do it?

thx so much!

**Comment by gordongrigor** [comment]
Its not natively implemented in Foxy; Humble contains changes for accelerated computing which bring significant performance improvements.  You could use a ROS bridge from Humble to Foxy for this.
