### ISSUE TITLE
No Synchronization point found

### ISSUE THREAD

**Issue by sandeepdutta** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_depth#16]
I have been trying to generate point clouds using this package.
I am using images generated by a ZED Mini camera . I keep getting the warning message below.
I have double checked the left & right images have exactly the same timestamp.
Any suggestions or insight as to what this error message means ?

Sandeep

[component_container_mt-1] 2023-10-13 18:28:19.740 WARN  synchronization/synchronization.cpp@123: No synchronization point found from the incoming message queues in this tick

**Comment by jaiveersinghNV** [comment]
Could you verify that the left and right **camera info** messages also have exactly the same timestamp? The `ESSDisparityNode` subscribes to [4 topics](https://nvidia-isaac-ros.github.io/repositories_and_packages/isaac_ros_dnn_stereo_depth/isaac_ros_ess/index.html#ros-topics-subscribed) that must all be synchronized for correct operation.
