### ISSUE TITLE
No Pose frame found

### ISSUE THREAD

**Issue by sandeepdutta** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_depth#17]
I am repeated getting this Waring message. 
[component_container_mt-1] 2023-10-13 17:28:47.527 WARN  gems/pose_tree/pose_tree.cpp@500: No pose frame found with UID 0
[component_container_mt-1] [WARN] [1697243327.527222379] [NitrosPointCloud]: Setting frame_id=zedm_left_camera_optical_frame from NITROS msg

I have checked the TF tree the "zedm_left_camera_optical_frame" does exist and is being published.
Any ideas on how to solve this ?
Sandeep

**Comment by jaiveersinghNV** [comment]
Could you please retry this on the [latest release](https://nvidia-isaac-ros.github.io/releases/index#isaac-ros-2-0-0-october-18-2023)?
