### ISSUE TITLE
isaac_ros_gxf/share/isaac_ros_gxf/gxf/include/gxf/std/parameter_parser.hpp@181: Could not parse parameter 'pool' from 'pool'

### ISSUE THREAD

**Issue by robotville** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_depth#19]
I am receiving some parsing errors related to the ESS Inference app (isaac_ros_ess) -- which seems to be caused by this block of ess_inference.yaml becoming out of sync with the changes to ESS.cpp
```- type: nvidia::isaac::ESSInference
  parameters:
    output_name: frame
    pool: pool
    left_image_receiver: data_receiver_left
    right_image_receiver: data_receiver_right
    output_transmitter: data_transmitter
    confidence_transmitter: confidence_output
    output_adapter: adapter
    image_type: RGB_U8
    pixel_mean: [-128, -128, -128]
    normalization: [0.00392156862, 0.00392156862, 0.00392156862]
    standard_deviation: [0.5, 0.5, 0.5]
    max_batch_size: 1
    model_input_type: RGB_U8
    onnx_file_path: onnx_file_path_placeholder
    engine_file_path: engine_file_path_placeholder
    input_layers_name: [input_left, input_right]
    output_layers_name: [output_left, output_conf]
    preprocess_type: RESIZE
```
 FULL Error Message from running:
 `ros2 launch isaac_ros_ess isaac_ros_ess.launch.py engine_file_path:=~/workspaces/isaac_ros-dev/src/isaac_ros_dnn_stereo_depth/resources/ess.engine threshold:=0.9`
### IS BELOW:

[component_container_mt-1] [INFO] [1697940036.964333452] [disparity]: [NitrosNode] Exporting the final graph based on the negotiation results
[component_container_mt-1] [INFO] [1697940037.089529361] [disparity]: [NitrosNode] Wrote the final top level YAML graph to "/home/admin/workspaces/isaac_ros-dev/install/isaac_ros_ess/share/isaac_ros_ess/OUNJYGKWSH.yaml"
[component_container_mt-1] [INFO] [1697940037.089596808] [disparity]: [NitrosNode] Calling user's pre-load-graph callback
[component_container_mt-1] [INFO] [1697940037.089607298] [disparity]: [NitrosNode] Loading application
[component_container_mt-1] [INFO] [1697940037.089616505] [disparity]: [NitrosContext] Loading application: '/home/admin/workspaces/isaac_ros-dev/install/isaac_ros_ess/share/isaac_ros_ess/OUNJYGKWSH.yaml'
[component_container_mt-1] 2023-10-21 22:00:37.092 WARN  gxf/std/yaml_file_loader.cpp@1058: Using unregistered parameter 'left_image_input' in component ''.
[component_container_mt-1] 2023-10-21 22:00:37.092 WARN  gxf/std/yaml_file_loader.cpp@1058: Using unregistered parameter 'right_image_input' in component ''.
[component_container_mt-1] 2023-10-21 22:00:37.092 WARN  gxf/std/yaml_file_loader.cpp@1058: Using unregistered parameter 'left_cam_input' in component ''.
[component_container_mt-1] 2023-10-21 22:00:37.092 WARN  gxf/std/yaml_file_loader.cpp@1058: Using unregistered parameter 'right_cam_input' in component ''.
[component_container_mt-1] 2023-10-21 22:00:37.092 WARN  gxf/std/yaml_file_loader.cpp@1058: Using unregistered parameter 'left_image_output' in component ''.
[component_container_mt-1] 2023-10-21 22:00:37.092 WARN  gxf/std/yaml_file_loader.cpp@1058: Using unregistered parameter 'right_image_output' in component ''.
[component_container_mt-1] 2023-10-21 22:00:37.092 WARN  gxf/std/yaml_file_loader.cpp@1058: Using unregistered parameter 'left_cam_output' in component ''.
[component_container_mt-1] 2023-10-21 22:00:37.092 WARN  gxf/std/yaml_file_loader.cpp@1058: Using unregistered parameter 'right_cam_output' in component ''.
[component_container_mt-1] 2023-10-21 22:00:37.092 ERROR /home/admin/workspaces/isaac_ros-dev/install/isaac_ros_gxf/share/isaac_ros_gxf/gxf/include/gxf/std/parameter_parser.hpp@181: Could not parse parameter 'pool' from 'pool'
[component_container_mt-1] [ERROR] [1697940037.092909879] [disparity]: [NitrosNode] LoadApplication Error: GXF_PARAMETER_PARSER_ERROR
[component_container_mt-1] terminate called after throwing an instance of 'std::runtime_error'
[component_container_mt-1]   what():  [NitrosNode] LoadApplication Error: GXF_PARAMETER_PARSER_ERROR

**Comment by hemalshahNV** [comment]
Was this run inside of the Isaac ROS Dev Docker container or on some other setup? The parameter parsing is very sensitive to the version of libyaml-cpp-dev that is installed on the system (needs to be 0.7.0).

**Comment by robotville** [comment]
I think upgrading libyaml-cpp-dev to 0.7.0 has fixed the problem thanks.
